version: '3.9'

services:
  oracle-database-free:
    image: container-registry.oracle.com/database/free:latest
    ports:
      - "$ORACLE_PORT:1521"
    environment:
      - ORACLE_PDB=$ORACLE_PDB
      - ORACLE_PWD=$ORACLE_PWD
      - ORACLE_CHARACTERSET=$ORACLE_CHARACTERSET
    volumes:
      - ./docker/oracle-data:/opt/oracle/oradata
